[package]
name = "gods_ui"
version = "0.1.0"
authors = ["Pawel Rynowiecki <pawel.rynowiecki@anixe.pl>"]
edition = "2018"

[dependencies]
itertools = "0.10.0"
bevy_egui = "0.1.3"
serde = "1.0.118"
serde_json = "1.0.61"